[build]
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.55.4"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1.environment]
HUGO_VERSION = "0.55.4"
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.4"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
